# gcp/cloud_storage/bucket_config.yaml

versioning:
  enabled: true

lifecycle:
  rule:
    - action:
        type: Delete
      condition:
        age: 365  # Deletes objects older than 365 days
    - action:
        type: SetStorageClass
        storageClass: NEARLINE
      condition:
        age: 30  # Changes storage class to NEARLINE after 30 days

logging:
  logBucket: gs://hermod-logging-bucket  # Replace with your logging bucket name
  logObjectPrefix: hermod-access-logs/
