# .github/workflows/security_scans.yaml

name: "Security Scans"

on:
  schedule:
    - cron: '0 3 * * 1'  # Runs every Monday at 03:00 UTC
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit safety

      - name: Run Bandit Security Linter
        run: |
          bandit -r src/ -f json -o bandit_report.json

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.json

      - name: Run Safety Vulnerability Checks
        run: |
          safety check -r requirements.txt --json > safety_report.json || true

      - name: Upload Safety Report
        uses: actions/upload-artifact@v3
        with:
          name: safety-report
          path: safety_report.json

      - name: Notify Security Issues
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Hermod Security Scan Failed"
          to: security-team@example.com
          from: hermod@example.com
          body: |
            Security scans have detected issues. Please review the attached reports.
          attachments: |
            bandit_report.json
            safety_report.json
